services:
  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: unga
      POSTGRES_PASSWORD: unga